# Generated by Django 3.2.13 on 2022-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_preferences', '0006_auto_20191001_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferencemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]

